# Generated by Django 3.2.9 on 2021-11-14 16:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('description', models.TextField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Dashboard',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='Dashboard', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Widgets',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('description', models.TextField(max_length=100)),
                ('need_auth', models.BooleanField(default=False)),
                ('positionColumn', models.IntegerField(null=True)),
                ('positionRow', models.IntegerField(null=True)),
                ('sizeColumn', models.IntegerField()),
                ('sizeRow', models.IntegerField()),
                ('catID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DashboardPage.categories')),
                ('dashboardID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DashboardPage.dashboard')),
            ],
        ),
        migrations.CreateModel(
            name='Weather',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('city', models.CharField(default='Toulouse', max_length=20)),
                ('cityID', models.IntegerField(null=True)),
                ('temp', models.IntegerField()),
                ('widgetID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DashboardPage.widgets')),
            ],
        ),
    ]
