# Generated by Django 3.2.9 on 2021-11-14 16:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('DashboardPage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboard',
            name='userID',
            field=models.ForeignKey(default=12, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
    ]
