# Generated by Django 3.2.9 on 2021-11-14 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DashboardPage', '0002_dashboard_userid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weather',
            name='widgetID',
        ),
        migrations.RemoveField(
            model_name='widgets',
            name='dashboardID',
        ),
    ]
