# Generated by Django 3.2.9 on 2021-11-14 18:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DashboardPage', '0003_auto_20211114_1844'),
    ]

    operations = [
        migrations.AddField(
            model_name='weather',
            name='widgetID',
            field=models.ForeignKey(default=99, on_delete=django.db.models.deletion.CASCADE, to='DashboardPage.widgets'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='widgets',
            name='dashboardID',
            field=models.ForeignKey(default=99, on_delete=django.db.models.deletion.CASCADE, to='DashboardPage.dashboard'),
            preserve_default=False,
        ),
    ]
