# Generated by Django 3.2.9 on 2021-12-03 20:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DashboardPage', '0005_settings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='widgets',
            name='dashboardID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dashboard', to='DashboardPage.dashboard'),
        ),
    ]
