# Generated by Django 3.2.9 on 2021-12-03 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DashboardPage', '0006_alter_widgets_dashboardid'),
    ]

    operations = [
        migrations.AddField(
            model_name='widgets',
            name='dashboardIT',
            field=models.ManyToManyField(related_name='dashboard2', to='DashboardPage.Dashboard'),
        ),
    ]
