# Generated by Django 3.2.9 on 2021-12-03 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DashboardPage', '0007_widgets_dashboardit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='widgets',
            name='dashboardIT',
        ),
        migrations.RemoveField(
            model_name='widgets',
            name='dashboardID',
        ),
        migrations.AddField(
            model_name='widgets',
            name='dashboardID',
            field=models.ManyToManyField(to='DashboardPage.Dashboard'),
        ),
    ]
