# Generated by Django 3.2.9 on 2021-12-03 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DashboardPage', '0008_auto_20211203_2117'),
    ]

    operations = [
        migrations.CreateModel(
            name='Opinion',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('rate', models.IntegerField()),
                ('description', models.TextField(max_length=200)),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='widgets',
            name='img',
            field=models.URLField(default='http://wedash.fr'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='widgets',
            name='rate',
            field=models.IntegerField(default=0),
        ),
    ]
