# Generated by Django 3.2.9 on 2021-12-03 22:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DashboardPage', '0009_auto_20211203_2159'),
    ]

    operations = [
        migrations.AddField(
            model_name='opinion',
            name='widgetID',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='DashboardPage.widgets'),
            preserve_default=False,
        ),
    ]
