# Generated by Django 3.2.9 on 2021-12-04 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DashboardPage', '0010_opinion_widgetid'),
    ]

    operations = [
        migrations.AddField(
            model_name='widgets',
            name='slug',
            field=models.SlugField(default='dehash', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='widgets',
            name='sizeColumn',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='widgets',
            name='sizeRow',
            field=models.IntegerField(null=True),
        ),
    ]
