# Generated by Django 3.2.9 on 2021-12-04 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DashboardPage', '0011_auto_20211204_0008'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Weather',
        ),
    ]
