# Generated by Django 3.2.9 on 2021-12-05 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DashboardPage', '0012_delete_weather'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='cmode',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='settings',
            name='dmode',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='settings',
            name='lang',
            field=models.CharField(default='French', max_length=20),
        ),
        migrations.AddField(
            model_name='settings',
            name='mail',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='settings',
            name='sms',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='settings',
            name='sound',
            field=models.BooleanField(default=False),
        ),
    ]
