# Generated by Django 3.2.9 on 2021-12-05 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DashboardPage', '0014_userinfos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfos',
            name='address',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='userinfos',
            name='city',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='userinfos',
            name='country',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='userinfos',
            name='phone',
            field=models.CharField(default='', max_length=15, null=True),
        ),
    ]
